package main

import (
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

func generate(options Options) error {
	if _, err := os.Stat(options.ProjectName); err == nil {
		return fmt.Errorf("directory %q already exists", options.ProjectName)
	} else if !errors.Is(err, os.ErrNotExist) {
		return err
	}

	files := filesFor(options)
	for _, file := range files {
		path := filepath.Join(options.ProjectName, file.Path)
		if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
			return err
		}
		contents, err := render(file.Body, options)
		if err != nil {
			return fmt.Errorf("render %s: %w", file.Path, err)
		}
		if err := os.WriteFile(path, []byte(contents), 0644); err != nil {
			return err
		}
	}
	return tidyGeneratedModule(options.ProjectName)
}

func tidyGeneratedModule(projectName string) error {
	command := exec.Command("go", "mod", "tidy")
	command.Dir = projectName
	command.Stdout = os.Stdout
	command.Stderr = os.Stderr
	if err := command.Run(); err != nil {
		return fmt.Errorf("run go mod tidy: %w", err)
	}
	return nil
}

func filesFor(options Options) []fileTemplate {
	files := []fileTemplate{
		{"go.mod", goModTemplate(options)},
		{"cmd/server/main.go", serverMainTemplate(options)},
		{"internal/config/config.go", `package config

// Config contains application configuration loaded from the environment.
type Config struct {
	Port string
}

func Load() Config {
	return Config{Port: "8080"}
}
`},
		{"web/static/css/app.css", `:root { color-scheme: dark; font-family: system-ui, sans-serif; }
body { margin: 0; min-height: 100vh; background: #15131a; color: #f3edf7; }
main { max-width: 72rem; margin: 0 auto; padding: 4rem 1.5rem; }
a { color: #e9a6ff; }
`},
		{"README.md", `# {{.ProjectName}}

Generated by [Gothify](https://github.com/fahmi-azzuhri/gothify).

## Stack

- Router: {{.Router}}
- Template: {{.Template}}
- CSS: {{.CSS}}
- Authentication: {{.Auth}}
- PWA: {{if .PWA}}enabled{{else}}disabled{{end}}
- Embedded assets: {{if .Embed}}enabled{{else}}disabled{{end}}

## Development

    go run ./cmd/server

Open http://localhost:8080.
`},
	}

	files = append(files, fileTemplate{"internal/auth/auth.go", authTemplate(options.Auth)})
	files = append(files, fileTemplate{"internal/httpserver/router.go", routerTemplate(options.Router)})
	files = append(files, fileTemplate{"web/templates/index.html", pageTemplate(options.Template)})
	if options.Template == "Go Templ + HTMX (native Go server-side rendering)" {
		files = append(files, fileTemplate{"web/templates/index.templ", `package templates

templ Index(projectName string) {
	<main>
		<h1>{ projectName }</h1>
		<button hx-get="/health" hx-target="#status">Check server</button>
		<p id="status">Ready.</p>
	</main>
}
`})
	}

	switch options.CSS {
	case "Tailwind CSS":
		files = append(files,
			fileTemplate{"tailwind.config.js", `/** @type {import('tailwindcss').Config} */
module.exports = { content: ["./web/templates/**/*.html"], theme: { extend: {} }, plugins: [] };
`},
			fileTemplate{"web/static/css/input.css", `@tailwind base;
@tailwind components;
@tailwind utilities;
`})
	case "Bulma / PicoCSS":
		files = append(files, fileTemplate{"web/static/css/vendor.css", `/* Add Bulma or PicoCSS through your preferred package manager. */
`})
	default:
		files = append(files, fileTemplate{"web/static/css/README.md", `This directory contains the plain CSS entrypoint for the project.
`})
	}

	if options.Template == "Go + Inertia.js (Go monolith with React/Vue)" {
		files = append(files,
			fileTemplate{"web/frontend/main.jsx", `import { createRoot } from "react-dom/client";

function App() {
  return <main><h1>{{.ProjectName}}</h1><p>Inertia entrypoint ready.</p></main>;
}

createRoot(document.getElementById("app")).render(<App />);
`},
			fileTemplate{"vite.config.js", `import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({
	plugins: [react()],
	build: { outDir: "web/frontend/dist", emptyOutDir: true },
	server: { host: "127.0.0.1", port: 5173 },
});
`})
	}
	if options.CSS == "Tailwind CSS" || options.Template == "Go + Inertia.js (Go monolith with React/Vue)" {
		files = append(files, fileTemplate{"package.json", packageJSON(options)})
	}

	if options.PWA {
		files = append(files,
			fileTemplate{"web/manifest.json", `{"name":"{{.ProjectName}}","short_name":"{{.ProjectName}}","start_url":"/","display":"standalone","background_color":"#15131a","theme_color":"#15131a"}
`},
			fileTemplate{"web/sw.js", `self.addEventListener("install", () => self.skipWaiting());
self.addEventListener("fetch", event => event.respondWith(fetch(event.request)));
`})
	}
	if options.Embed {
		files = append(files, fileTemplate{"web/assets.go", `package web

import "embed"

// Files contains the web assets inside the application binary.
//go:embed static/*
var Files embed.FS
`})
	}
	return files
}

func goModTemplate(options Options) string {
	dependencies := []string{}
	switch options.Router {
	case "Chi (lightweight and idiomatic Go)":
		dependencies = append(dependencies, "github.com/go-chi/chi/v5 v5.2.1")
	case "Fiber (Express-like and fast)":
		dependencies = append(dependencies, "github.com/gofiber/fiber/v2 v2.52.6")
	case "Echo (feature-complete and structured)":
		dependencies = append(dependencies, "github.com/labstack/echo/v4 v4.13.4")
	}
	if options.Template == "Go Templ + HTMX (native Go server-side rendering)" {
		dependencies = append(dependencies, "github.com/a-h/templ v0.2.778")
	}
	switch options.Auth {
	case "JWT + Refresh Token":
		dependencies = append(dependencies, "github.com/golang-jwt/jwt/v5 v5.2.2")
	case "OAuth2 (Google / GitHub via Goth)":
		dependencies = append(dependencies, "github.com/markbates/goth v1.80.0", "golang.org/x/oauth2 v0.27.0")
	}
	var output strings.Builder
	fmt.Fprintf(&output, "module %s\n\ngo 1.23\n", options.Module)
	if len(dependencies) > 0 {
		output.WriteString("\nrequire (\n")
		for _, dependency := range dependencies {
			fmt.Fprintf(&output, "\t%s\n", dependency)
		}
		output.WriteString(")\n")
	}
	return output.String()
}

func packageJSON(options Options) string {
	devDependencies := `"vite":"latest","@vitejs/plugin-react":"latest"`
	dependencies := `"@inertiajs/react":"latest","react":"latest","react-dom":"latest"`
	if options.Template != "Go + Inertia.js (Go monolith with React/Vue)" {
		devDependencies = `"tailwindcss":"^3.4.0"`
		dependencies = ``
	}
	if options.CSS == "Tailwind CSS" && options.Template == "Go + Inertia.js (Go monolith with React/Vue)" {
		devDependencies += `,"tailwindcss":"^3.4.0"`
	}
	scripts := fmt.Sprintf(`"dev":"%s"`, devScript(options))
	if options.Template == "Go + Inertia.js (Go monolith with React/Vue)" {
		scripts += `,"build":"vite build","preview":"vite preview"`
	}
	if options.CSS == "Tailwind CSS" && options.Template == "Go + Inertia.js (Go monolith with React/Vue)" {
		scripts += `,"css":"tailwindcss -i ./web/static/css/input.css -o ./web/static/css/app.css --watch"`
	}
	return fmt.Sprintf(`{"private":true,"scripts":{%s},"dependencies":{%s},"devDependencies":{%s}}
`, scripts, dependencies, devDependencies)
}

func devScript(options Options) string {
	if options.Template == "Go + Inertia.js (Go monolith with React/Vue)" {
		return "vite"
	}
	return "tailwindcss -i ./web/static/css/input.css -o ./web/static/css/app.css --watch"
}
